### ISSUE TITLE
Unexpected Error: node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js:95:23

### ISSUE THREAD

**Issue by 787681277** [jordanpowell88/angular-ct#46]
The error is displayed when run "npx cypress open --component" on Angular 13 with "cypress": "^10.3.1",

import { defineConfig } from "cypress";
import { devServer } from 'cypress-angular-dev-server';

export default defineConfig({
  component: {
    devServer,
    specPattern: 'src/**/*.cy.ts',
  },
  e2e: {
    specPattern: 'cypress/e2e/**/*.cy.{ts,js}'
}

});

<img width="1197" alt="Screen Shot 2022-08-11 at 21 12 03" src="https://user-images.githubusercontent.com/26969223/184141751-c7c94157-c8be-499c-9966-52d83d3c2ce2.png">

By the way, can you add a tag "angular 13" to download source code?

**Comment by jordanpowell88** [comment]
Thanks for filing the issue @787681277 I will be deprecating this project very soon as this will be released as 1st class support in cypress in our next release

**Comment by 787681277** [comment]
What’s release date for cypress next release for supported angular? I very need this

**Comment by jordanpowell88** [comment]
Next week!
